/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miage.spacelib.miagespacelibadmin;

import java.util.ArrayList;
import java.util.List;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miage.spacelib.services.ServiceAdminRemote;

/**
 *
 * @author Clem
 */
public class InterfaceAdmin extends javax.swing.JFrame {
    
    private final ServiceAdminRemote services;
    private List<String> stations = new ArrayList<>();
    private Etat Etat;
    
    private enum Etat {
        Etat_initial,
        Etat_AjoutStation
    }

    /**
     * Creates new form InterfaceAdmin
     */
    public InterfaceAdmin(ServiceAdminRemote sv) {
        initComponents();
        this.services = sv;
        this.Etat = Etat.Etat_initial;
        fillTableStation();
    }
    
    public void fillTableStation () {
        DefaultTableModel model = (DefaultTableModel) jTableStation.getModel();
        this.stations = this.services.getStations();
        for(int i = 0; i < stations.size(); i++) {
            String rowData[] = { "" };
            rowData[0] = stations.get(i);
            model.addRow(rowData);
        }
        this.jTableStation.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelStation = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableStation = new javax.swing.JTable();
        jLabelTableStation = new javax.swing.JLabel();
        jPanelAjout = new javax.swing.JPanel();
        jLabelNomStation = new javax.swing.JLabel();
        jTextFieldNomStation = new javax.swing.JTextField();
        jLabelCoordonneesStation = new javax.swing.JLabel();
        jTextFieldCoordonneesX = new javax.swing.JTextField();
        jTextFieldCoordonneesY = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonAjouterStation = new javax.swing.JButton();
        jLabelNbNavettes = new javax.swing.JLabel();
        jSpinnerNbNavette = new javax.swing.JSpinner();
        jPanelTrajet = new javax.swing.JPanel();
        jPanelMeca = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableStation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStation.setToolTipText("");
        jScrollPane.setViewportView(jTableStation);

        jLabelTableStation.setText("Table Station :");

        jPanelAjout.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajout de Station"));

        jLabelNomStation.setText("Nom de la station :");

        jLabelCoordonneesStation.setText("Coordonnées X , Y :");

        jLabel2.setText(",");

        jButtonAjouterStation.setText("Ajouter Station");
        jButtonAjouterStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterStationActionPerformed(evt);
            }
        });

        jLabelNbNavettes.setText("Nombre de navette :");

        jSpinnerNbNavette.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanelAjoutLayout = new javax.swing.GroupLayout(jPanelAjout);
        jPanelAjout.setLayout(jPanelAjoutLayout);
        jPanelAjoutLayout.setHorizontalGroup(
            jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjoutLayout.createSequentialGroup()
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAjoutLayout.createSequentialGroup()
                            .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNomStation)
                                .addComponent(jLabelCoordonneesStation))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNomStation, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelAjoutLayout.createSequentialGroup()
                                    .addComponent(jTextFieldCoordonneesX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCoordonneesY, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelAjoutLayout.createSequentialGroup()
                            .addComponent(jLabelNbNavettes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerNbNavette, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonAjouterStation, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelAjoutLayout.setVerticalGroup(
            jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAjoutLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomStation)
                    .addComponent(jTextFieldNomStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCoordonneesStation)
                    .addComponent(jTextFieldCoordonneesX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCoordonneesY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbNavettes)
                    .addComponent(jSpinnerNbNavette, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAjouterStation)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanelStationLayout = new javax.swing.GroupLayout(jPanelStation);
        jPanelStation.setLayout(jPanelStationLayout);
        jPanelStationLayout.setHorizontalGroup(
            jPanelStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationLayout.createSequentialGroup()
                .addGroup(jPanelStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabelTableStation, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStationLayout.setVerticalGroup(
            jPanelStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationLayout.createSequentialGroup()
                .addComponent(jLabelTableStation)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanelAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Gestion Station", jPanelStation);

        javax.swing.GroupLayout jPanelTrajetLayout = new javax.swing.GroupLayout(jPanelTrajet);
        jPanelTrajet.setLayout(jPanelTrajetLayout);
        jPanelTrajetLayout.setHorizontalGroup(
            jPanelTrajetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanelTrajetLayout.setVerticalGroup(
            jPanelTrajetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Gestion Trajet", jPanelTrajet);

        javax.swing.GroupLayout jPanelMecaLayout = new javax.swing.GroupLayout(jPanelMeca);
        jPanelMeca.setLayout(jPanelMecaLayout);
        jPanelMecaLayout.setHorizontalGroup(
            jPanelMecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanelMecaLayout.setVerticalGroup(
            jPanelMecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Gestion Mecanicien", jPanelMeca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterStationActionPerformed
        String nom = this.jTextFieldNomStation.getText();
        if (nom.matches(".*\\d+.*") || nom == "") {
            JOptionPane.showMessageDialog(this, "Le nom de la station ne doit pas etre vide ou contenir de caractères spéciaux.");
            this.jTextFieldNomStation.setText("");
        }
        try {
            float x = Float.parseFloat(this.jTextFieldCoordonneesX.getText());
            float y = Float.parseFloat(this.jTextFieldCoordonneesY.getText());
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Les coordonnées doivent etre des entiers.");
            this.jTextFieldCoordonneesX.setText("");
            this.jTextFieldCoordonneesY.setText("");
        }
        int nbNav = (int) this.jSpinnerNbNavette.getValue();
        
        System.out.println(nbNav);
        //this.services.creerStation(nom, x, y, );
    }//GEN-LAST:event_jButtonAjouterStationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    RMIAdminServiceManager rmiMgr = new RMIAdminServiceManager();
                    new InterfaceAdmin(rmiMgr.getAdminRemoteSvc()).setVisible(true);
                }catch(NamingException ex){
                    System.err.println("Erreur d'initialisation RMI : " + ex.getMessage());
                    System.err.println(ex.getExplanation());
                }              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterStation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCoordonneesStation;
    private javax.swing.JLabel jLabelNbNavettes;
    private javax.swing.JLabel jLabelNomStation;
    private javax.swing.JLabel jLabelTableStation;
    private javax.swing.JPanel jPanelAjout;
    private javax.swing.JPanel jPanelMeca;
    private javax.swing.JPanel jPanelStation;
    private javax.swing.JPanel jPanelTrajet;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSpinner jSpinnerNbNavette;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableStation;
    private javax.swing.JTextField jTextFieldCoordonneesX;
    private javax.swing.JTextField jTextFieldCoordonneesY;
    private javax.swing.JTextField jTextFieldNomStation;
    // End of variables declaration//GEN-END:variables
}
